### PR TITLE
Switch to a MIT-licensed dependency

### PR DESCRIPTION
**Pull request by DaniilGlazkoTR**
Openapi-schema-validator was using a GPL-licensed library **strict_rfc3339**, which might be incompatible with BSD. This pull request replaces strict_rfc3339 library with a different one - [rfc3339_validator](https://github.com/naimetti/rfc3339-validator). This library is licensed under MIT.

Jsonschema library has already been updated to include an option to use a different RFC3339 checker by [this Pull Request](https://github.com/Julian/jsonschema/pull/619).

### CODE REVIEW

**Comment by RafalSkolasinski** [comment]
@DaniilGlazkoTR Is there a reason for not merging this?

**Comment by arrdem** [comment]
Bumping this. Under the terms of the GPLv3 license, `openapi-schema-validator` and its dependees cannot be distributed or used under MIT terms because of this single dependency.

Is there anything else you'd like to see here before this gets merged @p1c2u?

**Comment by RafalSkolasinski** [comment]
@arrdem not sure about your use case but I jest went with https://github.com/Julian/jsonschema and it did work for my needs.
Taking into account that there were no commits and barely any activity in this repo in last 8 months probably it was a right decision

**Comment by arrdem** [comment]
@RafalSkolasinski yeah I was able to bang out a tiny bit of code that solved my actual problem just using jsonschema directly yesterday. Oh well.

**Review by AaronRobson — APPROVED** [review]

**Comment by AaronRobson** [comment]
Looks like this could do with a rebase to resolve the conflicts.

**Comment by DaniilGlazkoTR** [comment]
@AaronRobson, thanks for approving this PR. I've resolved the merge conflict, please consider merging it.

**Comment by AaronRobson** [comment]
> 
> 
> @AaronRobson, thanks for approving this PR. I've resolved the merge conflict, please consider merging it.

Would if I could, sadly I don't have permissions for that.

**Comment by DaniilGlazkoTR** [comment]
> > @AaronRobson, thanks for approving this PR. I've resolved the merge conflict, please consider merging it.
> 
> Would if I could, sadly I don't have permissions for that.

Right, my apologies, I was under the impression that only members with Write permissions can review PRs in this repo.

**Comment by p1c2u** [comment]
Why not use both as an option

**Pull request merged**
