### PR TITLE
Fix DeprecationWarning from jsonschema

### PR DESCRIPTION
**Pull request by lyang**
```python
        def iter_errors(self, instance, _schema=None):
            if _schema is not None:
                warnings.warn(
                    (
                        "Passing a schema to Validator.iter_errors "
                        "is deprecated and will be removed in a future "
                        "release. Call validator.evolve(schema=new_schema)."
                        "iter_errors(...) instead."
                    ),
                    DeprecationWarning,
                )
```
https://github.com/Julian/jsonschema/blob/main/jsonschema/validators.py#L189-L198

### CODE REVIEW

**Comment by rsokolovski-fincad** [comment]
LGTM

**Comment by p1c2u** [comment]
this requires requirements update for jsonschema to `jsonschema>=4.0.0`

**Comment by sthagen** [comment]
> this requires requirement update for jsonschema to `jsonschema>=4.0.0`

I would support that … and maybe keep `requirements.txt` and dependency section in `setup.cfg` in sync.

**Comment by p1c2u** [comment]
fixes #22

**Comment by p1c2u** [comment]
Tests doesn't pass because of recursion errors

**Comment by sthagen** [comment]
Hm, the 2.7 test run failed because the attribute `evolve` is not where it should, right?

**Comment by lyang** [comment]
Thank you!

**Pull request merged**
